<a href="https://colab.research.google.com/github/najnin26/Python/blob/main/Tensorflow/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

**0-D Tensor**

In [ ]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


**1-D Tensor**

In [ ]:
tensor_one_d=tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


**2-D Tensor**

In [ ]:
tensor_two_d=tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


**3-D Tensor**

In [ ]:
tensor_3_d=tf.constant([
  [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]
    ])
print(tensor_3_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_3_d.shape)

(4, 2, 3)


In [ ]:
print(tensor_one_d.ndim)

1


**4-D Tensor**

In [ ]:
tensor_4_d=tf.constant([
 [
  [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]
    ],
[
  [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]
    ],
[
  [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]
    ],
])
print(tensor_4_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]], shape=(3, 4, 2, 3), dtype=int32)


**Type Casting**

In [ ]:
tensor_one_d=tf.constant([2,0,-3])
casted_1_d=tf.cast(tensor_one_d,dtype=tf.float16)
print(tensor_one_d)
print(casted_1_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)
tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float16)


In [ ]:
tensor_one_d=tf.constant([2,0,-3])
casted_1_d=tf.cast(tensor_one_d,dtype=tf.bool)
print(tensor_one_d)
print(casted_1_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


**Types of Tensors**

In [ ]:
tensor_bool=tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string=tf.constant("Hello World")
print(tensor_string)

tf.Tensor(b'Hello World', shape=(), dtype=string)


In [ ]:
tensor_string=tf.constant(["Hello World","Hi"])
print(tensor_string)

tf.Tensor([b'Hello World' b'Hi'], shape=(2,), dtype=string)


**Numpy array to Tensor Conversion**

In [ ]:
import numpy as np

In [ ]:
array=np.array([1,2,3])
print(array)

[1 2 3]


In [ ]:
converted_tensor=tf.convert_to_tensor(array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
